# Generated by Django 2.1 on 2018-10-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181004_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identificacion',
            field=models.IntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
