# Generated by Django 2.1 on 2018-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181004_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_administrador',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('alertacliente', models.CharField(max_length=50)),
                ('alertaproducto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_operador',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
            ],
        ),
    ]
